version: 2.1
jobs:
  release:
    docker:
      - image: cimg/node:18.12.1
    steps:
      - checkout
      - run: npm install
      - run: npm run semantic-release
workflows:
  build_and_test:
    jobs:
      - release:
          context: dev-workflows-release
